# Generated by Django 4.0.7 on 2022-08-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flag', models.ImageField(upload_to='images/flags/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wikipedia_link', models.CharField(max_length=200)),
                ('twitter_handle', models.CharField(blank=True, default=None, max_length=20)),
                ('logo', models.ImageField(upload_to='images/logos/')),
                ('number_of_championships', models.PositiveIntegerField(default=0)),
                ('first_race_date', models.DateField(null=True)),
                ('first_race', models.CharField(max_length=200, null=True)),
                ('other_achievements', models.TextField()),
                ('total_races', models.PositiveIntegerField(default=0)),
                ('total_podiums', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.country')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('wikipedia_link', models.CharField(max_length=200)),
                ('twitter_handle', models.CharField(max_length=20, null=True)),
                ('photo', models.ImageField(upload_to='images/drivers/')),
                ('number_of_championships', models.PositiveIntegerField(default=0)),
                ('first_race_date', models.DateField(null=True)),
                ('first_race', models.CharField(max_length=200, null=True)),
                ('last_race', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.DateField()),
                ('other_achievements', models.TextField()),
                ('total_races', models.PositiveIntegerField(default=0)),
                ('total_podiums', models.PositiveIntegerField(default=0)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.country')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.team')),
            ],
        ),
    ]
