# Generated by Django 4.0.7 on 2022-10-17 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flag', models.ImageField(upload_to='images/flags/')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('wikipedia_link', models.URLField()),
                ('twitter_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(upload_to='images/drivers/')),
                ('number_of_championships', models.PositiveIntegerField(default=0)),
                ('number_of_wins', models.PositiveIntegerField(default=0)),
                ('first_race_date', models.DateField(null=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(blank=True, default=None, null=True)),
                ('total_races', models.PositiveIntegerField(default=0)),
                ('total_podiums', models.PositiveIntegerField(default=0)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.country')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('wikipedia_link', models.URLField()),
                ('twitter_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(upload_to='images/logos/')),
                ('number_of_championships', models.PositiveIntegerField(default=0)),
                ('number_of_wins', models.PositiveIntegerField(default=0)),
                ('first_race_date', models.DateField(null=True)),
                ('total_races', models.PositiveIntegerField(default=0)),
                ('total_podiums', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.country')),
            ],
            options={
                'ordering': ('-active',),
            },
        ),
        migrations.CreateModel(
            name='SeasonResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('points', models.FloatField(blank=True, default=0, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.driver')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.team')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ManyToManyField(to='champions.team'),
        ),
    ]
