# Generated by Django 4.0.7 on 2022-08-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='years_active',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created',
        ),
        migrations.RemoveField(
            model_name='team',
            name='years_active',
        ),
        migrations.AddField(
            model_name='driver',
            name='first_race',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='first_race_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='first_race',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='first_race_date',
            field=models.DateField(null=True),
        ),
    ]
