# Generated by Django 4.0.7 on 2022-10-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonresults',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seasonresults',
            name='race',
        ),
        migrations.AddField(
            model_name='seasonresults',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
