# Generated by Django 4.0.7 on 2022-08-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='last_race',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='other_achievements',
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_death',
            field=models.DateField(blank=True, default=None),
        ),
    ]
