# Generated by Django 4.0.7 on 2022-10-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-active',)},
        ),
    ]
