# Generated by Django 4.0.7 on 2022-09-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='first_race',
        ),
        migrations.RemoveField(
            model_name='team',
            name='first_race',
        ),
        migrations.AddField(
            model_name='driver',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='number_of_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='number_of_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='number_of_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='number_of_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='wikipedia_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='wikipedia_link',
            field=models.URLField(),
        ),
    ]
