# Generated by Django 4.0.7 on 2022-10-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='season_points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='team',
            name='number_of_ratings',
        ),
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
