# Generated by Django 4.0.7 on 2022-08-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_remove_driver_years_active_remove_team_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_race',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
