# Generated by Django 4.0.7 on 2022-10-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_tweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
