# Generated by Django 4.0.7 on 2022-08-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_remove_driver_last_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_of_death',
            field=models.DateField(default=None, null=True),
        ),
    ]
