# Generated by Django 4.0.7 on 2022-09-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_remove_driver_first_race_remove_team_first_race_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='other_achievements',
        ),
    ]
