# Generated by Django 4.0.7 on 2022-11-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_remove_seasonresults_date_remove_seasonresults_race_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/drivers/'),
        ),
        migrations.AddField(
            model_name='team',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/logos/'),
        ),
    ]
