# Generated by Django 4.0.7 on 2022-08-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0003_driver_active_driver_last_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='twitter_handle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_handle',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
