# Generated by Django 4.0.7 on 2022-08-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0004_alter_driver_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
